# Generated by Django 3.2.4 on 2021-06-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(default=15, verbose_name='Insert your age'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
