# Generated by Django 3.2.4 on 2021-06-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSys', '0002_auto_20210612_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Insert your age'),
        ),
    ]
