# Generated by Django 3.2.4 on 2021-07-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSys', '0003_alter_myuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
